### ISSUE TITLE
Large, big, tall, small, tiny and short should be on the ban list

### ISSUE THREAD

**Issue by krihal** [inclusivenaming/org#10]
The words large, big, tall, tiny, small and short should not be used and added to the toxic words ban list. We should all strive for a body positive world where the size of bodies or other things does not matter.

**Comment by Nytelife26** [comment]
> The words large, big, tall, tiny, small and short should not be used

How else do you describe the relative size of something, for instance, an array or data structure, without being exactly specific? Let's say you have something of indeterminate size, but you know it is \_\_\_\_. What would you use?

**Comment by dgrahn** [comment]
I'd second @Nytelife26. I looked up some synonyms of _large_ and they include worse terms - _sizeable, immense, enourmous, colossal, massive_. I think these might be the most neutral terms.

Do you have suggestions for alternatives?

**Comment by Nytelife26** [comment]
@krihal Do you have further comments or is this issue stale?

**Comment by krihal** [comment]
I did't think anyone would take this serious, close it.
