### ISSUE TITLE
Recommendation: man-in-the-middle attack

### ISSUE THREAD

**Issue by LarryKunz** [inclusivenaming/org#104]
Complete review for [man-in-the-middle attack](https://docs.google.com/document/d/1DRquJRyZXNxykZ6rh3P0GMhRmJfeEA8116hxbH1Wi5s/edit#heading=h.8wb1j12c0opl) recommendation and then publish as a Tier 3 term

**Comment by abuango** [comment]
Recommendation Published in https://inclusivenaming.org/word-lists/tier-3/man-in-middle/
