### ISSUE TITLE
Fix broken Wordlist download format

### ISSUE THREAD

**Issue by abuango** [inclusivenaming/org#118]
The ODT, PDF and HTML download format are broken for wordlist. This has been reported by members of the community.

**Comment by abuango** [comment]
@nate-double-u This ended up being a quick fix. The issue was with one of the dependencies needed to generate the file formats, the link was previously broken. I uncommented the build command and the formats download now. See https://github.com/inclusivenaming/website/pull/172/files

**Comment by nate-double-u** [comment]
Awesome, glad to hear it!
