### ISSUE TITLE
Slack

### ISSUE THREAD

**Issue by shaberrry** [inclusivenaming/org#19]
Hi @celestehorgan!
Unsure if you're the correct contact for this but I am experiencing the following issues:

- I am still unable to access the Slack. I am told "sshahedalqadi@gmail.com doesn’t have an account on this workspace".

- Secondly, my company (BMC Software) would like to know how to be listed on the [ Inclusive Naming site.](https://inclusivenaming.org/) Is there some specific way to be featured? 

Thanks so much,
Shahed

**Comment by justaugustus** [comment]
Thanks @shaberrry! I'm going to be sweeping the outstanding Slack invitations and will get you in today.
Apologies for the wait... it was not easy to verify who you were based on the email address and we're trying to be pretty strict about moderation.

**Comment by celestehorgan** [comment]
@shaberrry,

Hi! Can we close this issue?

**Comment by shaberrry** [comment]
Yes please!
