### ISSUE TITLE
Gather initial recommendations from participating member companies and reconcile

### ISSUE THREAD

**Issue by celestehorgan** [inclusivenaming/org#21]
At this point, most companies we're working with have already started the process of recommendation making. A key goal of this project is to create quorum on recommendations. 

Do the following:

1) Send out an email to call for existing recommendations
2) Compile into a spreadsheet
3) Reconcile and publish in a consistent format on the website.

Some things to keep in mind:

- [ ] Figure out how to guide people through the proper clearance processes with their existing companies
- [ ] Figure out the format we want to publish recommendations in

----

Issue https://github.com/inclusivenaming/org/issues/41 gathers public information that isn't from member companies.

**Comment by celestehorgan** [comment]
Carla, Joanna, Larry, Monica, Allyssa Yell

**Comment by celestehorgan** [comment]
cc: @quaid

**Comment by MonicaRush** [comment]
@celestehorgan My GitHub account is MonicaRush

**Comment by joannalee333** [comment]
@celestehorgan My GitHub account is joannalee333

**Comment by wordsmeanstuff** [comment]
@celestehorgan My GitHub account is wordsmeanstuff. Thanks!

**Comment by richsalz** [comment]
Here's Akamai's stance, perhaps interesting because it uses the phrase "unconscious bias" which I haven't seen mentioned much. https://ac.akamai.com/community/teams/marketing/marketing-announcements/blog/2020/06/22/checking-unconscious-bias-in-potentially-threatening-or-offensive-product-language  We have a draft internal doc that's not ready yet.

**Comment by LarryKunz** [comment]
My GitHub account is LarryKunz. Happy to be on this team.

**Comment by enygren** [comment]
My GitHub account is @enygren

**Comment by wordsmeanstuff** [comment]
I recently published this article in the Splunk Style Guide, if it's useful for coming up with recommendations and reconciliation. 

It lists:
- Determining whether a term shows bias
- Alternatives to biased language
- Documenting biased language that shows up in the product (when you can write around the terms) 

https://docs.splunk.com/Documentation/StyleGuide/current/StyleGuide/Inclusivity

**Comment by celestehorgan** [comment]
@wordsmeanstuff Hurray! I was hoping someone from Splunk was lurking in this group and that your style guide would be something we could reference! 😍

**Comment by wordsmeanstuff** [comment]
> @wordsmeanstuff Hurray! I was hoping someone from Splunk was lurking in this group and that your style guide would be something we could reference! 😍

Yes, of course! It would be awesome if we could get Splunk's logo on the main page as a participating organization, but maybe that involves a bit more work. Happy to help how I can, with the style guide and anything else!

**Comment by markcmiller86** [comment]
Assuming many are aware of this resource from Google but including for completeness...

https://developers.google.com/style/inclusive-documentation
