### ISSUE TITLE
Revisit the evaluation framework

### ISSUE THREAD

**Issue by celestehorgan** [inclusivenaming/org#24]
Now that the INI Language workstream has more members, let's revisit the evaluation framework and see if it still makes sense to the larger group.

Existing: https://inclusivenaming.org/language/evaluation-framework/

**Comment by celestehorgan** [comment]
Christopher, Carla, Joanna, Monica, Karsten, (Celeste)

**Comment by devries** [comment]
This is Christopher, and here is my github account.

**Comment by joannalee333** [comment]
This is Joanna volunteering to work on this issue

**Comment by quaid** [comment]
I'm in for working this task @quaid

One idea for the framework, perhaps we can add more to the third-order concerns? There are a few reasons for this:

1. "Is this the most descriptive word?" is an argument that sways some who are having a harder time understanding the concern in the first-order and second-order concerns.
2. Being inclusive also means non-native language speakers and readers need focus; where some people may not have the cultural background to appreciate the severity of a term, they might better understand that such a term is a barrier to people like themselves who are trying to understand and be understood in this language.
3. It provides an avenue for changing usage somewhere that doesn't (yet) consider the first-order and second-order concerns relevant or know how to handle them in their processes. In such cases, "It's a term that confuses our customers, how about this better term?" will at least address the harm of the term in a way that is universally actionable (there _will_ be a process for e.g. changing product terms that confuse customers), and may be a way to introduce the overall topic and process to organizations.
