### ISSUE TITLE
Marketing Standards

### ISSUE THREAD

**Issue by xmulligan** [inclusivenaming/org#29]
Create a standard around how people/companies can engage with inclusive naming for marketing purposes

**Comment by xmulligan** [comment]
Create a way for companies to show they are involved
Contributions from logo section
Companies that use inclusive naming, how to/maybe tie to case studies?
Create program for how companies can be involved and show their logo support even if they are not leading workstreams, etc. or super heavily involved
Evaluate a badging program

**Comment by hughgilmore08** [comment]
Standards work stream kickoff had a similar topic for discussion. Since I'm in both work streams I'm happy to liaise and flag potential duplicate work. It might make sense for marketing to propose the ideal logo/badging program, and standards can tap in on process to issue/audit?

**Comment by mschnoor-intel** [comment]
Agreed, standards workstream is interested as well.  It would be great to have this in place, so partnered SDOs to use INI logo in an appropriate manner, and be assigned a badge as well.
Think "Achievement Unlocked" but really more like "Commitment Secured".

**Comment by xmulligan** [comment]
the current response until the structure is set up:
Thank you for your interest in supporting the Inclusive Naming Initiative (INI). We request you to please secure clearance from your company's legal team to have your logo included on our website. You can reply to this email to confirm legal approval and then we will put your logo on our site.
Please note that INI is in process of incorporating as a legal entity in order to raise funds and manage our intellectual property. Once our structure is finalized, we will have a new process for organizations to show support for the initiative. We will reach out to you when that is the case and your company will have 90 days to follow the steps to stay as publicly-listed supporters. 
Best wishes,
The INI Team

**Comment by shahed-al** [comment]
H!
Emailing to confirm BMC's Legal approval.

[image: 1200px-BMC_Software_logo_(2014).svg.png]

**Comment by xmulligan** [comment]
@shahed-al can you make a PR of the logo in this folder and confirm that you have apporval there https://github.com/inclusivenaming/website/tree/main/static/img/logos?
