### ISSUE TITLE
Blog/Case Study template

### ISSUE THREAD

**Issue by xmulligan** [inclusivenaming/org#31]
Now that our blog is live, we need guidelines on how people can submit their work and add case studies

**Comment by xmulligan** [comment]
@oshratn

I've been thinking about blog posts for the work group today.
Do we require a blogpost to set the stage? It would explain why inclusive language is important and give examples of dos and dont's like the NIST and Microsoft pages and all the other ones that can be found with a simple internet search.
I am aware that the framework setup by the workgroup includes some of this. Is it detailed enough and is its reach wide enough?

What I really would like to do is get the stories behind the stories.
Those would be the stories of the people in organizations that have introduced inclusive language initiatives. It would be interesting to learn why they care, what their obstacles were and how they overcame them.
These pieces would potentially allow the readers to see themselves in them and involve them more, on an emotional level.

This looks like it would require a ticket on the board, but I do not have access to create one.

To-do: Find the leaders of inclusive language in organizations in our eco-system and interview them.

So do you see this as one blog post or a series of blog posts?

I see this as a series.

**Comment by Oshratn** [comment]
I reached out to Bryan Liles as the first prospect for an interview about language and its effects on (in his case) black software engineers.
I'd like to get to a point where there are at least three interviews in the backlog in order for it to be a bonafide series.

If you have ideas of prospects (preferably engineers) that are making our environment more diverse ad care about the language, I'd be grateful for a lead or better yet an intro.

In addition, as another series, running in conjunction with this one would be to find the leaders of initiatives on inclusive language. This would allow us to put their learnings and work-product in the forefront.

**Comment by xmulligan** [comment]
This is great! I am also putting together an introductory blog post and I think it would be good to weave this into what is going on in #42

**Comment by xmulligan** [comment]
@Oshratn I've put together a first draft of the kick off https://docs.google.com/document/d/1AgMxAz7WqyecjHkQ-3zF0d_Wnswm2rwEL-MlNHDG_ig/edit

How is your series coming?

**Comment by Oshratn** [comment]
@xmulligan I will be circling back to set up a time with Bryan, hopefully in the coming week, which will be the first installment of the series. That being said, I have yet to find other potential interviewees.

Which is a nice segue into - Iwas thinking we might add yet another CTA to your blog post in which we can also ask people to step up and tell the stories around inclusive language in their organizations. WDYT?

**Comment by xmulligan** [comment]
@Oshratn I think that would be a great idea! I've added a suggestion to the kick off https://github.com/inclusivenaming/website/pull/43/files#r607773751

Let me know if you want something else or have a better suggestion on how to word it

**Comment by lotusleafstyle** [comment]
@xmulligan hey Bill - did the blog post go up? :) So excited to see it live! 🙂

**Comment by xmulligan** [comment]
@lotusleafstyle Not yet, Celste needs to make a change to make it go live and I'm waiting on her https://github.com/inclusivenaming/website/pull/43

**Comment by xmulligan** [comment]
@lotusleafstyle it is now online! 
https://inclusivenaming.org/blog/_posts/welcome-post/

**Comment by xmulligan** [comment]
@Oshratn I am going to close this issue. I think it would be better to organize the blog posts as individual issues otherwise this one will never be closed since we would like to continue keeping the drum beat up

**Comment by xmulligan** [comment]
case study program will be tracked in #46
