### ISSUE TITLE
Media package

### ISSUE THREAD

**Issue by xmulligan** [inclusivenaming/org#32]
Elevator pitch and messaging 25-50-100 character points
Stats? LoC changed? 
Media mentions section on the website

**Comment by xmulligan** [comment]
https://docs.google.com/document/d/1DmtQio65v2tz3zsCyZQOY9fpA82Q4AXTjJEXpsHm4Cw/edit?usp=sharing

**Comment by lotusleafstyle** [comment]
> https://docs.google.com/document/d/1DmtQio65v2tz3zsCyZQOY9fpA82Q4AXTjJEXpsHm4Cw/edit?usp=sharing

Can we change this link to: https://docs.google.com/document/d/1_AHADPNC-VFN7LxsMfEU27jzEXkTaNZ5AD-WosLqF9o/edit

**Comment by xmulligan** [comment]
@lotusleafstyle I've removed the other link, do you want me to add it to the markeing folder in the google drive?

**Comment by lotusleafstyle** [comment]
Sounds perfect!

**Comment by xmulligan** [comment]
@lotusleafstyle it seems I don't have the permission to move it, but you can add the file to the folder here https://drive.google.com/drive/folders/1KL-xvUy-KAwBpShmrvQ8k7yUpboEwDrc

**Comment by celestehorgan** [comment]
@xmulligan – can we close this?

**Comment by xmulligan** [comment]
@celestehorgan we are still working on this, can there be a "media" section on the website where we can host this information?

**Comment by xmulligan** [comment]
Should we have a PowerPoint template too? Other presentations? Branding and logos?
