### ISSUE TITLE
Adjust google drive permissions for ws leads 

### ISSUE THREAD

**Issue by joannalee333** [inclusivenaming/org#35]
Please adjust permissions for workstream leads in the INI google drive folder so we can invite workstream members to read, write, and edit.  Currently we are able to create new folders but are not able to invite workstream members to upload documents or edit the contents of those folders.

**Comment by justaugustus** [comment]
I've created a ws-all list (all WS MLs + leads@) which has been granted [`Contributor`](https://support.google.com/a/answer/7337554?hl=en) access to the `public/` folder within the shared drive.

The shared drive directory listing is as follows:

![Screenshot from 2021-03-06 00-47-23](https://user-images.githubusercontent.com/567897/110196888-8f636180-7e15-11eb-95cc-f23d041c3cb2.png)

Root
- leads
- public
  - logos
  - workstreams
    - Community
    - Company
    - Language
    - Marketing
    - OSS
    - Standards

As a note, it should not be necessary to delegate individual access to a document. If you:
1. create the document within the `public/` folder
2. ensure the contributor is a member of one of the WS mailing lists.

Let me know if you have any issues!

cc: @celestehorgan @edwarnicke @pritianka @xmulligan @MonicaRush @mschnoor-intel @andrepellet
