### ISSUE TITLE
Gather currently public recommendations and reconcile

### ISSUE THREAD

**Issue by celestehorgan** [inclusivenaming/org#41]
At this point, most companies we're working with have already started the process of recommendation making. A key goal of this project is to create quorum on recommendations.

This issue collects **publicly available recommendations and style guides for inclusive language**, regardless of whether there are participants in our org. 

Please:
1) Post publicly accessible guidelines you know exist 
2) Provide any credit or attribution we know of.

Related to: https://github.com/inclusivenaming/org/issues/21, which will collect non-public guidelines we know of.

**Comment by markcmiller86** [comment]
Assuming many are aware of this resource from Google but including for completeness...

https://developers.google.com/style/inclusive-documentation
