### ISSUE TITLE
Marketing: Social Media Presence 

### ISSUE THREAD

**Issue by shahed-al** [inclusivenaming/org#42]
Talks of a blog are taking place in the Marketing WS, so I would like to propose [building out a LinkedIn Page](https://www.linkedin.com/help/linkedin/answer/710/create-a-linkedin-page?lang=en) for Inclusive Naming to publish these blogposts (I believe Bill is working on drafting something but I may be mistaken). LinkedIn is a great place to lay the groundwork regarding professional visibility

The timeline would be as follows:

- have brand resources prepared (logo, banner, imagery, etc.)
- create a linkedin page & share it wherever possible to create a following
- draft a launch blog introducing the initiative
- increase visibility by sharing blogs other companies are posting that mention inclusive naming (my company did [a brief one](https://www.bmc.com/blogs/inclusion-is-better-for-business/))
- down the line, we could create co-postings with companies that are involved in order to grow the initative more

**Comment by lmaffeo** [comment]
@shahed-al I think a LinkedIn page to host blogs is a great idea. Are there plans to publish on an owned blog as well and syndicate that blog content on LinkedIn for promotion? Or would all content live on LinkedIn as the main platform?

**Comment by xmulligan** [comment]
@celestehorgan is currently working on putting the blog on the website https://github.com/inclusivenaming/website/pull/31

@shahed-al I love this timeline

**Comment by justaugustus** [comment]
This is awesome!
@xmulligan -- As the conversation evolves, I want to make sure that we've got the page/link locked in: https://www.linkedin.com/company/inclusive-naming

Added you, @celestehorgan, and @pritianka as admins.

**Comment by celestehorgan** [comment]
@xmulligan – I called for review on my blog PR last week; since there's nothing I'll merge it in.

**Comment by xmulligan** [comment]
https://github.com/inclusivenaming/website/pull/43 PR for the first blog post

**Comment by xmulligan** [comment]
We have made the LinkedIn page and created the first couple posts. @justaugustus can you close this issue.

Further work will be in #52 and creating other blog posts

**Comment by justaugustus** [comment]
SGTM. Thanks Bill!
