### ISSUE TITLE
Unable to join WS- Mailing lists

### ISSUE THREAD

**Issue by spotz** [inclusivenaming/org#43]
When going to join the various WS- mailing lists for example:
https://groups.google.com/u/1/a/inclusivenaming.org/g/ws-oss
https://groups.google.com/u/1/a/inclusivenaming.org/g/ws-language

We are receiving the following:

Content unavailable

Click here to try again.
If you've seen this page more than once, try switching accounts, or check with your organization's administrator to make sure you have permission.

**Comment by edwarnicke** [comment]
@justaugustus Any updates on this?  I'm happy to go figure things out if you point me in the right direction :)

**Comment by justaugustus** [comment]
Infra (private) repo PR up, which hopefully fixes this: https://github.com/inclusivenaming/ini-infra/pull/3

**Comment by mschnoor-intel** [comment]
The changes look good to me.
