### ISSUE TITLE
Curate a registry/guide for known (independant) tools for DEI/language

### ISSUE THREAD

**Issue by celestehorgan** [inclusivenaming/org#60]
## The Problem

Provide a resource for other organizations for known OSS projects in the DEI and language space. Executing on this task includes doing the research on these projects. 

This would also help INI identify tooling gaps that we could help fill in future. 

## Requirements 

- Research known OSS projects in this space
- Produce a document that lists each project and provides a brief description.

## Blockers 

None known

**Comment by dtzar** [comment]
We've spent some time researching all of the available tools/resources in this space and happy to share.

**Comment by celestehorgan** [comment]
Dale's idea: create a table, have people PR against it

**Comment by celestehorgan** [comment]
Closed" https://github.com/inclusivenaming/org/blob/main/ws-oss/tooling.md
