### ISSUE TITLE
Quick note about "Big endian" and "Little endian"

### ISSUE THREAD

**Issue by markcmiller86** [inclusivenaming/org#66]
I got worred these terms might have sprung from [Ten little indians](https://en.wikipedia.org/wiki/Ten_Little_Indians) but [this ref](https://www.ling.upenn.edu/courses/Spring_2003/ling538/Lecnotes/ADfn1.htm) as well as [this one](https://www.rfc-editor.org/ien/ien137.txt) say otherwise. Worth knowing in case it ever comes up.

**Comment by Humbedooh** [comment]
My understanding has always been that this refers to Gulliver's Travels and the fight over which `end` of an egg to eat from, hence `end-ian`. To my recollection, the Big Endians prefer to open the big end (what we generally perceive as the bottom of an egg), and the Little Endians prefer opening the little end, what is commonly called the top of the egg. This was then applied to binary representation of numbers, wherein little and big end represents where to put the end and beginning of numbers in binary format. If someone asks about this, perhaps a short note such as this will suffice?

**Comment by markcmiller86** [comment]
> If someone asks about this, perhaps a short note such as this will suffice?

Sure thing. I guess I am no where near as well read as everyone else 😆
