### ISSUE TITLE
Unique names in software project sources

### ISSUE THREAD

**Issue by sanliturk** [inclusivenaming/org#7]

**Comment by sanliturk** [comment]
I have studied in your web site . It seems that the main goal is to define a friendly language ( not to harmful to persons ) in project ( let's say ) documentations .


I am tracking a large number of software projects .


There is another big problem in software projects , either they are open sourced or closed sourced but with published libraries  .

The trouble is the following  :  In many projects , routines , functions , constants , global variables are named arbitrarily , and they are not compilable together .

In general , software parts are compiled ( in Make files ) one by one . Then , they are combined in a library . Such a compilation is concluding successfully .

When I combine all of the library sources into a source file as included files , and try to compile it , it is producing a large number errors , and correcting them is not easy some times because they are conflicting with each other , but having the same and used in different places .

This is causing unrecognizable , uncorrectable   errors in software when they are combined together .

Another trouble point is that compilation quality and correctness is depending on "order of compilation and linking" ,
due to parts with same name but different contexts .

To remedy such difficulties requires a  "standard unique naming" convention among software projects .

As an example , consider LLVM and CLang .

All of the LLVM parts ( routines , functions , constants , global variables ) may start with llvm_ , and Clang with clang_ .
Prefixes llvm_ , clang_ ,  will be allocated by a voluntarily established organization such as "inclusiveNaming.org" , 
means no one else will use such prefixes for other purposes in other software projects . 

There are a huge number of very important projects which they are not using such a consistent part naming conventions .

Such an approach will reduce important problems of software developers and packages managers for ALL of the operating systems .

If you include such a service in your very good and appreciated efforts , it will make your contributions much more appreciated and will produce long lasting good effects .
 

Mehmet Erol Sanliturk

**Comment by LarryKunz** [comment]
This is a worthwhile suggestion. IMO, however, it's outside the scope of Inclusive Naming.

**Comment by sanliturk** [comment]
Thank you very much . Your needs and decisions are very respected by me .
I wonder whether you know a more related organization and if you know would you please forward my suggestion to them or 
if you supply me such a name(s) I can write to them for consideration of my suggestion .

**Comment by sanliturk** [comment]
I consider this problem important because I want to write / develop a C compiler based on compilation of sources with respect to 
their unique names of parts supplied in lists of pairs such as  (  unique_name_of part , source_file_name_of_part ) .
Such an approach will simplify compilations considerably especially in large scale program sources because for each library only its names lists will be supplied . It is possible to generate such renaming and name pairs lists , but , when they are
adopted by the library maintainers , such works will not be available to other compiler writers and users of libraries for
their compilations .

**Comment by sanliturk** [comment]
"
when they are
adopted by the library maintainers , such works will not be available to other compiler writers and users of libraries for
their compilations .
"

I am sorry , the above part should be

"
when they are   NOT
adopted by the library maintainers , such works will not be available to other compiler writers and users of libraries for
their compilations .
"

**Comment by markcmiller86** [comment]
Unfortunately, the functionality needed by compilers in the way of symbol name mangling controls to avoid name collisions when large numbers of independently developed software packages are linked together in the same executable is far outside the scope of INI.

This is most often a problem with the *global* namespace. And, there are a number of community best practices for this and most widely adopted packages already employ some such practices (C++ namespaces, 3-4 letter leader in all public symbols, `-fvisibility_hidden`, etc.) in their development. Those that don't ought to be willing to accept pull requests from downstream consumers when collisions are found.

I recomend we close as out of scope.

**Comment by sanliturk** [comment]
Thank you very much for your explanations .
Based on your advise I am closing the issue with my best wishes for all of you and success in your operations .
