### ISSUE TITLE
TweetDeck access

### ISSUE THREAD

**Issue by justaugustus** [inclusivenaming/org#80]
(@xmulligan reached to add a few contributors to TweetDeck, so filing this to track the request for posterity.)

> Can you add @oshratn Shahed to the INI Tweetdeck?
They are members of the marketing WS and have been regular participants

**Comment by justaugustus** [comment]
The following users are already Admins:
- @xmulligan 
- @edwarnicke 
- @pritianka 
- @justaugustus 

Recently accepted requests:
- @celestehorgan (Admin)
- @oshratn (Contributor)

Received the following message on trying to add Shahed:
> That user has privacy settings enabled preventing them from being added to this team.

From https://help.twitter.com/en/using-twitter/tweetdeck-teams:
> I’m not able to add a particular person to my team. What should I do?
>
> The person may have privacy settings enabled that prevents them from being added to a team. Talk to the team member to check whether this is the case. They can temporarily disable the setting in the Twitter for teams section through the [Your account](https://twitter.com/settings/account) settings page on twitter.com to accept a new invitation.

@xmulligan -- Given your access, you should be able to work with Shahed to resolve, but let me know if you both need any help.

**Comment by xmulligan** [comment]
Both Shahed and Oshrat have access now, thanks for the help!
