### ISSUE TITLE
Recommendation: black hat hacker

### ISSUE THREAD

**Issue by celestehorgan** [inclusivenaming/org#86]
Adapt IBM's recommendation for Black hat hacker and add it to the website

**Comment by quaid** [comment]
Process is essentially:

1. Convert recommendation from GDoc draft to MD file
2. Make PR for public comment period
3. Publish PR when public comment period is complete

**Comment by lex-joy** [comment]
Lauren and I made an initial submission for "[black hat hacker](https://github.com/inclusivenaming/org/pull/95)" today.

I don't think I put it in the correct directory, though -- if someone could move it to the proper location, I'd be much obliged.

**Comment by abuango** [comment]
Recommendation published in https://inclusivenaming.org/word-lists/tier-1/blackhat-whitehat/
